=== netgroup-polito/nfv-data-model/data-format/nfv/pni/pni.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
 Copyright (c) 2019 Enrico Cecchetti and Federico Gianno.
-->
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

    <xsd:include schemaLocation="./../xml_components.xsd"/>

    <xsd:element name="PNI">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="Hosts" minOccurs="1" maxOccurs="1"/>
                <xsd:element ref="Connections" minOccurs="0" maxOccurs="1"/>
            </xsd:sequence>
        </xsd:complexType>
        <!-- key reference definitions -->
        <xsd:key name="hostKey">
            <xsd:selector xpath="Hosts/Host" />
            <xsd:field xpath="@id" />
        </xsd:key>
        <xsd:unique name="ConnectionUniqueness">
            <xsd:selector xpath="Connections/Connection"/>
            <xsd:field xpath="@sourceHost"/>
            <xsd:field xpath="@destHost"/>
        </xsd:unique>
        <xsd:keyref name="ConnectionSourceHost" refer="hostKey">
            <xsd:selector xpath="Connections/Connection" />
            <xsd:field xpath="@sourceHost" />
        </xsd:keyref>
        <xsd:keyref name="ConnectionDestHost" refer="hostKey">
            <xsd:selector xpath="Connections/Connection" />
            <xsd:field xpath="@destHost" />
        </xsd:keyref>
    </xsd:element>

    <!-- Hosts -->
    <xsd:element name="Hosts">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="Host" minOccurs="0" maxOccurs="unbounded"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <!-- Host -->
    <xsd:element name="Host">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="Computational_properties" type="Computational_propertiesType" minOccurs="0" maxOccurs="1" />
                <xsd:element name="Memory_properties" type="Memory_propertiesType" minOccurs="0" maxOccurs="1" />
                <xsd:element name="Network_properties" type="Network_propertiesType" minOccurs="0" maxOccurs="1" />
                <xsd:element name="V_Node_Ref" type="VNodeRefType" minOccurs="0" maxOccurs="unbounded"/>
                <xsd:element name="P_Node_Ref" type="PNodeRefType" minOccurs="0" maxOccurs="unbounded"/>
                <xsd:element name="SupportedVNF" type="SupportedVNFType" minOccurs="0" maxOccurs="unbounded"/>
            </xsd:sequence>
            <!-- <xsd:attribute name="name" type="xsd:string" use="required"/> -->
            <xsd:attribute name="id" type="xsd:string" use="required"/>
            <xsd:attribute name="fixedEndpoint" type="xsd:string" use="optional"/>
            <xsd:attribute name="active" type="xsd:boolean" use="optional" default="false"/>
            <xsd:attribute name="maxVNF" type="xsd:int" use="optional"/>
            <xsd:attribute name="type" type="TypeOfHost" use="optional"/>
        </xsd:complexType>
    </xsd:element>

    <xsd:complexType name="VNodeRefType">
        <xsd:attribute name="id" type="xsd:string" use="required"/>
    </xsd:complexType>

    <xsd:complexType name="PNodeRefType">
        <xsd:attribute name="id" type="xsd:string" use="optional"/>
    </xsd:complexType>

    <xsd:complexType name="SupportedVNFType">
        <xsd:attribute name="functional_type" type="functionalTypes" use="required" />
    </xsd:complexType>

    <xsd:simpleType name="TypeOfHost">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="CLIENT"/>
            <xsd:enumeration value="SERVER"/>
            <xsd:enumeration value="MIDDLEBOX"/>
        </xsd:restriction>
    </xsd:simpleType>

    <!-- Connection -->
    <xsd:element name="Connections">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="Connection" minOccurs="0" maxOccurs="unbounded"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="Connection">
        <xsd:complexType>
            <xsd:attribute name="sourceHost" type="xsd:string" use="required"/>
            <xsd:attribute name="destHost" type="xsd:string" use="required"/>
            <xsd:attribute name="avgLatency" type="xsd:int"/>
        </xsd:complexType>
    </xsd:element>

</xsd:schema>

=== netgroup-polito/nfv-data-model/out/artifacts/nfv_rest_war_exploded/WEB-INF/xsd/pni/pni.xml
<?xml version="1.0" encoding="UTF-8"?>
<PNI xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="pni.xsd">
	<Hosts>
		<Host id="hostA" type="CLIENT" fixedEndpoint="nodeA">
			<Computational_properties cpu="1000" cores="2" nOfOperations="10"/>
			<Memory_properties memory="4" disk_storage="10"/>
			<Network_properties bandwidth="20"/>
			<V_Node_Ref id="0"/>
		</Host>
		<Host id="hostC" type="SERVER" fixedEndpoint="nodeB">
			<Computational_properties cpu="1000" cores="2" nOfOperations="10"/>
			<Memory_properties memory="4" disk_storage="10"/>
			<Network_properties bandwidth="20"/>
			<P_Node_Ref id="0"/>
		</Host>
		<Host id="host1" maxVNF="1" type="MIDDLEBOX">
			<Computational_properties cpu="3000" cores="16"/>
			<Memory_properties memory="16" disk_storage="50"/>
			<Network_properties bandwidth="20"/>
			<SupportedVNF functional_type="FIREWALL"/>
			<SupportedVNF functional_type="CACHE"/>
			<SupportedVNF functional_type="FIELDMODIFIER"/>
		</Host>
		<Host id="host2" maxVNF="2" type="MIDDLEBOX">
			<Computational_properties cpu="4000" cores="4"/>
			<Memory_properties memory="16" disk_storage="20"/>
			<Network_properties bandwidth="20"/>
			<SupportedVNF functional_type="FIREWALL"/>
		</Host>
		<Host id="host3" maxVNF="3" type="MIDDLEBOX">
			<Computational_properties cpu="3000" cores="8"/>
			<Memory_properties memory="16" disk_storage="10"/>
			<Network_properties bandwidth="20"/>
			<SupportedVNF functional_type="CACHE"/>
			<SupportedVNF functional_type="FIELDMODIFIER"/>
		</Host>
		<Host id="hostB" type="SERVER" fixedEndpoint="nodeB">
		<Computational_properties cpu="1000" cores="2"/>
			<Memory_properties memory="2" disk_storage="10"/>
			<Network_properties bandwidth="20"/>
		</Host>
	</Hosts>

	<Connections/>

	<!-- 
	|nodeA|_______|node1|_______|node2|_______|nodeB|
						\_		_/   
						  \	   /     
			  |nodeC|_____|node3|____|nodeD|
	-->

</PNI>
